server:
  port: 8030

eureka:
  client:
    serviceUrl:
          defaultZone:  http://120.77.202.205:8080/eureka/  #注册中心地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/z475546259/SpringCloudConfigCenter.git
          searchPaths: demo* #搜索路径
#          username: username
#          password: password
  application:
    name: config-server